### ISSUE TITLE
Add depend a boot

### ISSUE THREAD

**Issue by gustavomonarin** [pi2schema/pi2schema#3]
Considering that the number of external dependencies can grow quite quickly depending of the directions the project can lead, would be great to have a bot checking the dependency versions.

Currently the code is already closely associated to apache kafka, confluent and protobuf artifacts.

This list can grow quickly to other serialization protocols as well as multiple key management systems

**Comment by juliano** [comment]
Done!

**Comment by gustavomonarin** [comment]
awesome :) 

What do you think about a badge on the Readme file containing the status?
